### ISSUE TITLE
Rename font family, replacing script name with something local

### ISSUE THREAD

**Issue by davelab6** [vaishnavimurthy/Akaya-Kannada#1]
We can't have the script name in the font family name, because it can be confusing when the font is subset and only contains Latin. 

Therefore please rename both font families, replacing script name with something local. Hind uses 'Mysuru' and Baloo uses 'Tamma'

Also filenames should reflect PS Names, with no version. 

You can rename files in git like this:

```
git mv AkayaKannada_1.0-Regular.ttf AkayaMysuru-Regular.ttf 
```

**Comment by vaishnavimurthy** [comment]
Hi Dave, I'll remove the version number from this. However, I'm a bit
confused about the local name. When I download the font and have it
working, It'll be useful to have the script name next to the font name.
Having names of cities or other local names I find is a bit confusing even
though it might work in the download context. Akaya Latin can say Akaya
Latin in that case. Do let me know if this sounds reasonable.

**Comment by davelab6** [comment]
> It'll be useful to have the script name next to the font name. 

The font is primarily intended for use on the web through Google Fonts API, and the 'default' font served by the API is a basic latin one; users must specify other scripts. 

So having a family named "Family Script" will be confusing because often the font will not contain anything for that script. 

> Having names of cities or other local names I find is a bit confusing even though it might work in the download context. Akaya Latin can say Akaya Latin in that case. Do let me know if this sounds reasonable.

There aren't any "Family Latin" names, since that would be including the script name in the family name :)

You could also use two different but related names, like "Akaya" and "Akayi" or something like that

**Comment by vaishnavimurthy** [comment]
I was wondering if :  "Akaya" for Latin, "Akayaಅಕಯ" for Kannada and
"Akayaఅకయ" for Telugu could be a possibility. Here the Name is repeated in
the respective scripts.

**Comment by davelab6** [comment]
No, names have to be ASCII only

**Comment by davelab6** [comment]
@vaishnavimurthy what do you think?

**Comment by vaishnavimurthy** [comment]
Hi Dave,

Its unfortunate that the font names can support only ASCII. I didn't know
about this.

I have a couple of ok names, but still a bit unsure of how this works. I
personally find it confusing to have names that are a bit ambiguous as I
mentioned earlier and I still don't have supporting names that solves this.

Here's what I understand so far:
- The Google fonts API will serve-up the character-set for a selected
  script. So, a 'Hind Mysuru' might not have the Kannada characters included
  when viewed under Latin but appears with the same name 'Hind Mysuru'.
- If this API lists all the fonts that contain Latin, then, you'll have
  several Hinds (Hind Guntur, Hind Colombo etc.,) having the same Latin
  characters but under different names.
- This might be as confusing for the user as having the FamilyName +
  Script don't you think? Maybe I'm wrong, but this is what I understand
  so-far.
- I did look at how the API works right now and I see the complete
  character-set which includes the second script even when I choose Latin.

Is Akaya+Kan & Akaya+Tel a possibility :) I'm trying this one last time!

**Comment by davelab6** [comment]
> Its unfortunate that the font names can support only ASCII. I didn't know about this.

Its possible to localise font name items in the name table, so that they appear in a font picker's family list if that picker is savvy to use them; but some are not, and so ASCII font names are needed for those cases. 

> I have a couple of ok names, but still a bit unsure of how this works. I personally find it confusing to have names that are a bit ambiguous as I mentioned earlier and I still don't have supporting names that solves this.

Okay

> Here's what I understand so far:
> - The Google fonts API will serve-up the character-set for a selected script. So, a 'Hind Mysuru' might not have the Kannada characters included when viewed under Latin but appears with the same name 'Hind Mysuru'.

The important thing is that the unspecified case is latin only. That means if you use this,

```
<link href='https://fonts.googleapis.com/css?family=Hind+Siliguri' rel='stylesheet' type='text/css'>
```

you only get latin. 

If you use this, 

```
<link href='https://fonts.googleapis.com/css?family=Hind+Siliguri&subset=latin' rel='stylesheet' type='text/css'>
```

you only get latin. 

If you use this, 

```
<link href='https://fonts.googleapis.com/css?family=Hind+Siliguri&subset=latin,bengali' rel='stylesheet' type='text/css'>
```

you get Bengali (and latin, because there must always be a latin)

> - If this API lists all the fonts that contain Latin, then, you'll have several Hinds (Hind Guntur, Hind Colombo etc.,) having the same Latin characters but under different names.

Yes, you can see this today:

<img width="1634" alt="screen shot 2016-02-20 at 00 49 39" src="https://cloud.githubusercontent.com/assets/261579/13194790/2735c9e0-d76c-11e5-9b49-27088480577b.png">

> - This might be as confusing for the user as having the FamilyName + Script don't you think? Maybe I'm wrong, but this is what I understand so-far.

I think if you use this,

```
<link href='https://fonts.googleapis.com/css?family=Hind+Bengali' rel='stylesheet' type='text/css'>
```

then I think it is surprising that no Bengali is included, because it says Bengali. 

Similarly if you use this,

```
<link href='https://fonts.googleapis.com/css?family=Hind+Bengali&subset=latin,bengali' rel='stylesheet' type='text/css'>
```

it says Bengali twice. 

What if we added Cyrillic to "Akaya Kannada"? If you used this,

```
<link href='https://fonts.googleapis.com/css?family=Akaya+Kannada&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
```

It could also be surprising that there is no Kannada. 

> - I did look at how the API works right now and I see the complete character-set which includes the second script even when I choose Latin.

I expect you looked in Chrome or Firefox or Opera, which support the CSS `unicode-range` property. This allows the entire font's character set to be split into **non overlapping** mini-fonts that the browser requests one by one based on which characters are in the page. So the second script's characters are not downloaded unless they need to be, and no `&script=` link option is needed. 

However, there is a collision between `unicode-range`'s requirement that the mini-fonts be non-overlapping, and the way Unicode expresses south asian scripts with shared unicode characters (ie, overlapping.) 

Therefore we can only support one south asian script in each family, unless the CSS specification is updated to handle multi-south-asian-script fonts, and browsers then implement that specification. This will take a few years. 

> Is Akaya+Kan & Akaya+Tel a possibility :) I'm trying this one last time!

I don't think so; the point is that indicating the script directly in the family name conceptually collides with the requirement to specify the script in the `&subset=` link option for pre-unicode-range browsers. 

This

```
<link href='https://fonts.googleapis.com/css?family=Akaya+Kan' rel='stylesheet' type='text/css'>
```

indicates the script but doesn't produce a font that supports that script, and this

```
<link href='https://fonts.googleapis.com/css?family=Akaya+Kan&subset=latin,kannada' rel='stylesheet' type='text/css'>
```

indicates the script twice. 

Another option is 2 different names that are conceptually related. Eg
- "blood" and "tears" 
- "river" and "lake"
- "oil" and "water"

**Comment by vaishnavimurthy** [comment]
Thanks for this Dave, its much clearer now.

I finally understand how the three issues of : 1. Unicode-range overlap; 2.
The need to define subsets; 3. default Latin download on not defining
subset for multi script families is creating all the confusion. If only the
'default = Latin' could be changed to 'default = entire font' :) I will add
a second name to the two fonts in the hope of a unified font 5 years later!

I'm sure you've put a lot of thought into this, however, I'm sharing a few
of my amateur opinions below since I came across them:

Having separate South Asian and non-South Asian files would make it easier
to sort the scripts for use. This is as opposed to having it bundled-up
under another script. This will especially be useful while using multiple
South-Asian scripts. For example, if I need to use Akaya :
Cyrillic+Latin+Latin Ext.+Telugu,Kannada; I'll be able to download :

_Akaya_ ( Latin+Latin Ext.+Cyrillic)

<link href='https://fonts.googleapis.com/css?family=Akaya&subset=*latin,latin-ext,cyrillic*'
rel='stylesheet' type='text/css'>

*Akaya Kannada *(Latin+Kannada) (I'll just stick with Kannada and Telugu
here to make it easier)

<link href='https://fonts.googleapis.com/css?family=Akaya+Kannada&subset=*latin,kannada*'
rel='stylesheet' type='text/css'>

_Akaya Telugu_ (Latin+Telugu)
<link href='https://fonts.googleapis.com/css?family=Akaya+Telugu&subset=
*latin,telgu*' rel='stylesheet' type='text/css'>

This is as opposed to having two font files and not remembering under which
name I've included Cyrillic / Latin.ext :

*Akaya Kannada *(Latin+Latin Ext.+Cyrillic+Kannada)

<link href='https://fonts.googleapis.com/css?family=Akaya+Kannada&subset=*latin,cyrillic,kannada*'
rel='stylesheet' type='text/css'>

_Akaya Telugu_ (Latin+Latin Ext.+Cyrillic+Telugu)
<link href='https://fonts.googleapis.com/css?family=Akaya+Telugu&subset=
*latin,latin.ext,telgu*' rel='stylesheet' type='text/css'>

I see the advantage of being able to download all of them in the same file.
It's just a matter of setting the default sub-set in the 'quick use' window
which'll make it easier to sort the scripts within the downloaded fonts.

I see now why you insist on having a second name, but I still don't fully
understand why the script name cannot appear twice. I doubt there'll be
many people who will want to manually alter the subset for Kannada in the
CSS snippet that appears with the subset script name by default in the
quick use window This will work better if there's a separate file for
Latin++ in my opinion. For those who take the trouble to type
'family=Akaya+Kannada' in the CSS, as opposed to 'family=Akaya' should be
aware of including 'subet=latin,kannada' :) (I know how time consuming
sorting these things are and I'm point this out as mere observations for
the time being.)

Having said this, there might be a flaw here: If I have Latin Ext.
downloaded with Akaya Telugu and I use this with Akaya Kannada's Latin,
will the kerning values between Latin and Latin Ext. remain intact? The
alternative is to enable Latin.ext by default, which doesn't happen now.

Unrelated to this, I wanted to share a few things I was looking at in the
API:

As a user of multiple scripts, I would find it useful to see a 'scripts
supported' stamp in the API for choosing a font that supports the scripts
I'll be using. Right now, I'll have to manually check for this and I'm
pretty clueless as to which are the multi script / single script fonts.
Especially when the family name does not indicate this on searching for it.

Having all the scripts a typeface supports in the following screen which
downloads multiple font files might also be useful. This could extend to
CSS/ links for multiple files in the same window for different scripts.
This could also sort the download/CSS options to make it as efficient as
possible as indicated in the example above.

I was also wondering the need for having the 'see all styles' button. The
card format seems pretty intuitive to me to enable this.

On adding multiple fonts to a collection, I cannot easily go to quick use
screen to choose the script/character-set. Also, the collections drawer at
the bottom gets lost and I was under the impression that only download was
possible from the top right button after choosing the fonts for a long time.

I'll update my fonts with the names soon. Thanks once again Dave.

**Comment by davelab6** [comment]
> > What if we added Cyrillic to "Akaya Kannada"?
> 
> Having separate South Asian and non-South Asian files would make it easier to sort the scripts for use

Yes, I think you are right :) 

> For those who take the trouble to type 'family=Akaya+Kannada' in the CSS, as opposed to 'family=Akaya' should be aware of including 'subet=latin,kannada' :)

"Should", sure. But they won't! The support questions come to me, and this is a real problem for people... its a common cognitive bias to assume that others know what you know. 

> Having all the scripts a typeface supports

I agree that the scripts dropdown should be like the categories one.

> If I have Latin Ext. downloaded with Akaya Telugu and I use this with Akaya Kannada's Latin, will the kerning values between Latin and Latin Ext. remain intact?

Today, Kerning doensn't work across font files, and thus unicode range breaks kerning, so even a regular latin/latin-ext family in Chrome has kerning issues. 

> the need for having the 'see all styles' button

Do you mean to remove it, or expand it by default? 

> On adding multiple fonts to a collection, I cannot easily go to quick use screen to choose the script/character-set. 

Yes you can, but clicking "use" at the bottom-right

> the collections drawer at the bottom gets lost 

Not sure what you mean, there is a `>` icon to expand it if you collapse it. 

> and I was under the impression that only download was possible from the top right button after choosing the fonts for a long time.

You mean the download button was there but it took you a while to notice it? That is intentional, as it nudges people towards using fonts on the web as web fonts instead of as images-of-text.

**Comment by davelab6** [comment]
> I'll update my fonts with the names soon. 

Looking forward to what you come up with :D

**Comment by davelab6** [comment]
Please do let me know the name in the next day or so :)

**Comment by davelab6** [comment]
This repo is now https://github.com/vaishnavimurthy/Akaya-Kanadaka/  and there is https://github.com/vaishnavimurthy/Akaya-Telivigala so closing :)
